### ISSUE TITLE
Complement pipeline will currently use the latest Synapse release when building on branch `master`

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/complement#141]
When running Complement tests against Synapse in CI, the current Complement [buildkite pipeline code](https://github.com/matrix-org/pipelines/blob/d0381b28f361ccd726aca883933a5fd32a8b39f4/complement/pipeline.yml#L29) will check to see if a similarly-named branch exists on Synapse's repo.

As is often the case, if the name of the branch is `master`, we'll end up looking for a branch named `master` on Synapse's side which then grabs the latest *release* of Synapse, rather than Synapse's `develop` branch.

This can cause CI to fail on Complement `master` while the latest release of Synapse does not support tests that are intended to be run against Synapse `develop`. We saw this recently with `TestKnocking`, which then magically fixed itself after Synapse 1.37.0 was released today.

The fix is to insert some bash to say "if $BUILDKITE_BRANCH is `master`, use Synapse `develop`".

**Comment by clokep** [comment]
This was fixed in #191. It now runs against a matching branch name or `develop`.
