### ISSUE TITLE
sytest-coverage: Coverage script is broken after cs-api revamping

### ISSUE THREAD

**Issue by meenal06** [matrix-org/complement#183]
**Describe the bug**

Coverage script can no longer be run because of the cs-api directory added.

**To Reproduce**
- Run the `go run ./cmd/sytest-coverage`

**Expected behavior**

Sytest coverage should be outputted

**Screenshots**
```
panic: ./tests/csapi:1:1: illegal UTF-8 encoding (and 1 more errors)

goroutine 1 [running]:
main.main()
	/Volumes/T7/code/complement/cmd/sytest-coverage/main.go:56 +0xf45
exit status 2
```

**Comment by meenal06** [comment]
Hey @kegsay can I work on fixing this?

**Comment by kegsay** [comment]
Yes, go for it!
