### ISSUE TITLE
Synapse tests run against `master` branch instead of `develop` by default

### ISSUE THREAD

**Issue by kegsay** [matrix-org/complement#184]
``` 
=== RUN   TestRestrictedRoomsRemoteJoinLocalUser
    msc3083_test.go:191: Deploy times: 6.570039ms blueprints, 3.985522787s containers
    client.go:370: POST hs2/_matrix/client/r0/createRoom => 200 OK (226.771354ms)
    client.go:370: POST hs2/_matrix/client/r0/createRoom => 400 Bad Request (5.686334ms)
    msc3083_test.go:204: CSAPI.MustDo POST http://172.17.0.1:49305/_matrix/client/r0/createRoom returned HTTP 400
```

https://github.com/matrix-org/complement/runs/3180791920#step:7:1029

**Comment by kegsay** [comment]
The actual problem here is ` 2021-08-03 08:20:34,574 - synapse.http.server - 88 - INFO - POST-1 - <SynapseRequest at 0x7f8584d6ba00 method='POST' uri='/_matrix/client/r0/createRoom' clientproto='HTTP/1.1' site='8008'> SynapseError: 400 - Your homeserver does not support this room version`

**Comment by clokep** [comment]
Is this actually flaky or does the corresponding Synapse PR just need `develop` merged into it?

**Comment by kegsay** [comment]
I'm not sure, all I know is it's failing on `master` and for PRs which is annoying and frustrating.

**Comment by clokep** [comment]
> I'm not sure, all I know is it's failing on master and for PRs which is annoying and frustrating.

Thanks for clarifying that it is failing on master, I couldn't tell where that build is from.

I wonder if this is a case of us using the wrong branch to test against?

**Comment by clokep** [comment]
Confirmed that https://github.com/matrix-org/complement/runs/3304194643 checked out the right branch and tests passed. 🎉
