### ISSUE TITLE
Make `Sync*` functions validate sync response

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/complement#243]
Currently functions such as `SyncUntil` do little to validate the JSON they're actually getting, I think it could be an easy win to develop a generic validation function, which walks the entire sync response and validates it, before handing it back to the caller.

**Comment by kegsay** [comment]
It's not the job of helper functions to do test validation. Tests do test validation. If you want to test /sync response shapes or validate keys on it, they should be written as actual tests.
