### ISSUE TITLE
Think about adding `sync_next_batch` equivalent variable to `CSAPI`

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/complement#247]
While looking through sytests, there seems to be a concept of storing/updating the `next_batch` of previous syncs with user objects (`CSAPI` objects in complement)

This could be quite helpful when "checkpointing" sync to a particular moment in the test fairly easily.

However, i suspect that adding this would be a massive breaking internal change, as every test in complement has basically acted with `since: null` up until this point.

Either that, or add an additional `bool` to every `Sync*` function which signifies if it should try to `cont`inue from the last-stored `next_batch` variable.

**Comment by kegsay** [comment]
https://github.com/matrix-org/complement/pull/272
