### ISSUE TITLE
[test] `sync_filter_test.go` tests addition and removal of filters, but doesn't verify it working

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/complement#252]
Title, `msc2716_test.go` does use filters for its functionality, but `sync_filter_test.go` doesnt test filters by itself, nor different types or configurations.

**Comment by kegsay** [comment]
Please do not make issues for "hey, we don't test X, we should test X", particularly if the test isn't a regression test else this issue tracker would be very large indeed.

**Comment by ShadowJonathan** [comment]
Alright, noted
