### ISSUE TITLE
Support sytests with deprecated endpoints?

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/complement#258]
While converting tests, I came upon the following ones;

```
./tests/80torture/03events.pl:test "GET /events with negative 'limit'",
./tests/80torture/03events.pl:test "GET /events with non-numeric 'limit'",
./tests/80torture/03events.pl:test "GET /events with non-numeric 'timeout'",
./tests/80torture/03events.pl:test "GET /initialSync with non-numeric 'limit'",
```

`/events` and `/initialSync` have long-been deprecated according to the spec, should I still be converting these? Or can i add some sort of "excluded" marker next to them? (and build that into the `sytest-coverage` tool)

**Comment by kegsay** [comment]
No, don't test deprecated endpoints. If a sytest is _using_ a deprecated endpoint then that test should be updated. If a sytest is _testing_ a deprecated endpoint then it can be safely skipped.

**Comment by ShadowJonathan** [comment]
What about sytest coverage? Should i edit it to add the exclusion bit?

**Comment by kegsay** [comment]
Yeah, we shouldn't be taking deprecated tests into account when working out the % parity.

**Comment by ShadowJonathan** [comment]
Alright, while i think it's easy to remove it from the list and PR that, i'll make a change to sytest-coverage to instead see if a line is suffixed with an `X`, and then exclude that line.

This way we can also track which tests were ignored explicitly, instead of having to dig through git history
