### ISSUE TITLE
Use `gotestfmt` for output

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/complement#268]
https://github.com/haveyoudebuggedit/gotestfmt

I hope two simple images can illustrate why;

![image](https://user-images.githubusercontent.com/22740616/145106651-c5a3b04c-655a-4eae-9fc2-1d7668c7dd78.png)
![image](https://user-images.githubusercontent.com/22740616/145106661-0ab625e6-38bc-450d-8535-d2e65a16e73f.png)

**Comment by kegsay** [comment]
I like it. Will experiment with it. Related: https://github.com/matrix-org/complement/issues/3

**Comment by ShadowJonathan** [comment]
Yeah, this formatter can also parse with json, but maybe a more custom solution would be even better, something that'd also print the corresponding homeserver logs alongside the output in an easier form to go through.

**Comment by kegsay** [comment]
I don't want to be maintaining the custom output where possible, so I'll see how bad it looks with just the defaults with gotestfmt

**Comment by janosdebugs** [comment]
Hey @kegsay @ShadowJonathan I've added an [issue](haveyoudebuggedit/gotestfmt#30) to allow for custom formatters for test output, maybe this helps? It would save you the trouble of having to parse the `go test` JSON output yourselves, but you could still format your own output as you see fit.
