### ISSUE TITLE
`JSONKeyEqual` will give confusing error message when comparing JSON numbers

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/complement#278]
> MatchResponse key 'matrix:image:size' got '2239' want '2239'

This is when using `JSONKeyEqual` on a `match.JSON` array.

Changing the error message section to the following;

```go
  if !reflect.DeepEqual(gotValue, wantValue) {
    return fmt.Errorf("key '%s' got '%v' (%T) want '%v' (%T)", wantKey, gotValue, gotValue, wantValue, wantValue)
  }
```

Yields this more useful error message;

> MatchResponse key 'matrix:image:size' got '2239' (float64) want '2239' (int)

This behaviour should probably be accounted for when extracting values with `JSONKeyEqual`, so either `JSONKeyEqual` will have to coerce all numerical types into `float64`, or give this above more-clear error message.

**Comment by kegsay** [comment]
Bleh, thanks for pointing this out. Agreed, test writers should not need to know or care about this.

**Comment by ShadowJonathan** [comment]
I got tripped up by this again today:

```golang
		PLContent := map[string]interface{}{
			"invite": 100,
			"users": map[string]interface{}{
				alice.UserID: 100,
			},
		}

		eventId := alice.SendEventSynced(t, roomID, b.Event{
			Type:     "m.room.power_levels",
			StateKey: b.Ptr(""),
			Content:  PLContent,
		})

		res := alice.MustDoFunc(
			t,
			"GET",
			[]string{"_matrix", "client", "v3", "rooms", roomID, "event", eventId},
		)

		must.MatchResponse(t, res, match.HTTPResponse{
			JSON: []match.JSON{
				match.JSONKeyEqual("content", PLContent),
			},
		})
```

> `MatchResponse key 'content' got 'map[invite:100 users:map[@alice:hs1:100]]' want 'map[invite:100 users:map[@alice:hs1:100]]'`

This fails because the integer inside the powerlevel event's content is converted to float64, so doing a roundtrip is not possible.

**Comment by ShadowJonathan** [comment]
One thing we can do is do a [canonicalisation roundtrip](https://blog.gojek.io/relooking-at-golangs-reflect-deepequal/) by `Marshal`ling and `Unmarshal` the compared-to `interface{}`, to make sure it matches the type quirks that reflect.DeepEquals needs.
