### ISSUE TITLE
Parse go test -json output

### ISSUE THREAD

**Issue by kegsay** [matrix-org/complement#3]
Into something that CI will understand and be useful.

**Comment by deepbluev7** [comment]
So one easy way to do this, is to use [gotestsum](https://github.com/gotestyourself/gotestsum) and use the resulting junit report. No idea, if that also works with github actions, but we use that here: https://gitlab.com/famedly/company/backend/services/synapse/-/merge_requests/11/diffs#587d266bb27a4dc3022bbed44dfa19849df3044c_29_44

You basically just replace `go test -v` with `gotestsum --junitfile report.xml --format standard-verbose` and you get a junit report.xml aswell as normal test output on stdout.
