### ISSUE TITLE
Support testing Synapse with Postgres

### ISSUE THREAD

**Issue by babolivier** [matrix-org/complement#323]
https://github.com/matrix-org/synapse/pull/12024 raised the issue that, since the images we use for Synapse only support SQLite, we might be missing some pretty bad bugs. In this specific case, Complement shows Synapse's implem as passing whereas it's actually broken for any instance using PostgreSQL (which should be most Synapse instances). It sounds to me like we could really benefit from having Dockerfiles and config files for Synapse that support Postgres.

**Comment by kegsay** [comment]
https://github.com/matrix-org/dendrite/blob/main/build/scripts/ComplementPostgres.Dockerfile is what Dendrite does.

**Comment by babolivier** [comment]
> This is really a subset of testing Synapse with worrkers (https://github.com/matrix-org/complement/issues/194)

Is it? Being able to test with PostgreSQL would have raised https://github.com/matrix-org/synapse/pull/12024 even without workers support afaict.

**Comment by richvdh** [comment]
It's a subset in that, if we test with workers, we will necessarily be testing with Postgres too. I'm not saying there wouldn't be advantages to testing with Postgres as a monolith too.

**Comment by babolivier** [comment]
Ah right, gotcha, thanks for clarifying.
