### ISSUE TITLE
`generate_signing_key: not found` error in `Synapse.Dockerfile` for any synapse older than 1.54

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/complement#332]
Via https://github.com/matrix-org/complement/pull/328 and https://github.com/matrix-org/synapse/pull/12118

(1.54 is technically not out yet, but the latter PR puts it on develop for that release)

**Comment by DMRobertson** [comment]
The underlying root cause is https://github.com/matrix-org/complement/issues/330.

**Comment by DMRobertson** [comment]
Going to close this as done: the config to make Synapse interplay with complement is now versioned within Synapse (#330/#359).
