### ISSUE TITLE
TestJoinViaRoomIDAndServerName assumes the homeserver will extract domain names from room IDs

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/complement#39]
https://github.com/matrix-org/complement/blob/8cbf8752e18dae94ec8e95cdf07f5e4ee6c67d0a/tests/federation_room_join_test.go#L56-L58

Room IDs are meant to be treated as opaque strings, and thus homeservers are not supposed to extract domain names from them. Having a test that relies on this functionality does not seem right.

(Yes, Dendrite will currently extract domain names from room IDs as a last resort).

**Comment by oliverpool** [comment]
> Room IDs are meant to be treated as opaque strings, and thus homeservers are not supposed to extract domain names from them. 

How is the homeserver supposed to find another homeserver knowing about the room?
I couldn't find anything in the [spec](https://matrix.org/docs/spec/server_server/r0.1.4#joining-rooms)

It reads:

> In summary, the remote join handshake consists of the joining server querying the directory server for information about the room alias; receiving a room ID and a list of join candidates. The joining server then requests information about the room from one of the residents. It uses this information to construct a m.room.member event which it finally sends to a resident server.

But I can't understand how the `directory server` gets discovered.

**Comment by anoadragon453** [comment]
In the case of [`POST /_matrix/client/r0/join/{roomIdOrAlias}`](https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-join-roomidoralias), the client can provide a list of `server_name` query parameters as a hint to the homeserver on which servers to attempt to join the room through. When someone shares a link to a room (who is already in it), they can include some known server names in that link.

As for [`POST /_matrix/client/r0/rooms/{roomId}/join`](https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-rooms-roomid-join), which doesn't have an equivalent query parameter; the server will need to be in the room already.

**Comment by oliverpool** [comment]
All right, thank you for your explanations.

I think I understand now. There are two issues for the same behavior (no way to set the `server_name` query parameter):
- during blueprint deployment (tracked in #38)
- during test with `CSAPI.JoinRoom` (tracked here)
