### ISSUE TITLE
Error handling in constructHomeserver could be unified

### ISSUE THREAD

**Issue by oliverpool** [matrix-org/complement#41]
Considering this code (with 2 places where an `err != nil` can happen):

https://github.com/matrix-org/complement/blob/9acaf3cd28e2d32024c80a3f04105e2cce7ff1e3/internal/docker/builder.go#L269-L284

If the deploy fails (first `err != nil`) it gets logged to the standard output via `log.Printf` (and `printLogs` is called explicitely).
If the runner fails, it gets logged to the Builder (and `printLogs` is called by the parent).

I think those 2 error logging should be unified: what do you think is the best approach?

I would recommend having some logging to the standard output, since it can impact the rest of the test.

For instance adding an `err` param to `printLogs`, which will get printed at the end of the server log if not `nil`, called inside `construct`.

I would be glad to make a PR for this.

---

Background info: I am trying to understand how #39 can be fixed, and I discovered that the Blueprints has an error (but only after spending a couple of hours and finally adding `COMPLEMENT_DEBUG=1` :)
```
2020/11/17 22:57:42 federation_one_to_one_room.hs2 : failed to run instructions: federation_one_to_one_room.hs2 : request http://localhost:32902/_matrix/client/r0/join/%21IiiKfQGoJGEqTPCTXN:hs1?access_token=MDAxMWxvY2F0aW9uIGhzMgowMDEzaWRlbnRpZmllciBrZXkKMDAxMGNpZCBnZW4gPSAxCjAwMWJjaWQgdXNlcl9pZCA9IEBib2I6aHMyCjAwMTZjaWQgdHlwZSA9IGFjY2VzcwowMDIxY2lkIG5vbmNlID0gbjNjbkNJeUs7bmxhMFBubAowMDJmc2lnbmF0dXJlIGjnOvc29ANDh6mwUukBi_1NocFirh6_gE1ZoogwQotxCg returned HTTP 404 Not Found : {"errcode":"M_UNKNOWN","error":"No known servers"}
```

**Comment by Kegsay** [comment]
I don't think this requires a structural change so much as needing the error logged when not using `COMPLEMENT_DEBUG=1`. I don't like the idea of `printLogs` also printing errors because... it's convenient? I'm happy to shuffle about the logging since it can be improved, particularly at blueprint deployment time.

**Comment by oliverpool** [comment]
> I don't like the idea of printLogs also printing errors because... it's convenient?

I see this the other way around: when there is an error, I also want `printLogs` to be called. That way I can understand the error much better and be able to debug faster.

3 of the 4 `printLogs` calls are in case of an error (the 4th one being called when `t.Failed()` is true).

I can make 2 functions: `printErrorWithLogs` and `printLogs` to allow for a clearer separation of concerns. What do you think?

---

_should such discussions happen here or in [#complement:matrix.org](https://matrix.to/#/#complement:matrix.org) ?_

**Comment by oliverpool** [comment]
And shouldn't be deployment errors always reported?

Otherwise on may start investigating the test failure, without knowing that some setup of the blueprint did failed previously and might be the root cause for the later test failure.

**Comment by Kegsay** [comment]
Deployment errors should always be reported, it is a bug if they aren't.

Discussions should probably happen here for later reference.

**Comment by oliverpool** [comment]
> Deployment errors should always be reported, it is a bug if they aren't.

In this case it probably needs a bigger refactoring, so that any error in [`construct`](https://github.com/matrix-org/complement/blob/9acaf3cd28e2d32024c80a3f04105e2cce7ff1e3/internal/docker/builder.go#L214) gets returned and prevents the test from running.

If you agree, I can take a look at this.

**Comment by Kegsay** [comment]
Sounds good to me!
