### ISSUE TITLE
`Search_works_across_an_upgraded_room_and_its_predecessor` is flaky

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/complement#478]
https://github.com/matrix-org/synapse/actions/runs/3081667619/jobs/4982001564

Ported from sytest in https://github.com/matrix-org/complement/pull/464

**Comment by richvdh** [comment]
> if we think a test is just plain wrong, raise in complement

Moving to the complement repo, then.

**Comment by richvdh** [comment]
https://github.com/matrix-org/synapse/actions/runs/3130081166/jobs/5079975834

**Comment by DMRobertson** [comment]
Another one here: https://github.com/matrix-org/synapse/actions/runs/3126059365/jobs/5071114994
