### ISSUE TITLE
TestMediaWithoutFileName test does not allow changes in content type between media upload and download

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/complement#49]
The tests:

* `Can download without a file name locally`
* `Can download without a file name over federation`

that are a part of `TestMediaWithoutFileName` both have a check for the `Content-Type` header value that was provided during initial upload of the test media. They ensure this value does not change between uploading and downloading media and its associated metadata.

Synapse will however [augment the content type](https://github.com/matrix-org/synapse/pull/7044/files) of text files in order to specify UTF-8 as their encoding. The reasoning behind this is at https://github.com/matrix-org/synapse/issues/7043.

While the spec doesn't [explicitly state](https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-media-r0-download-servername-mediaid) that the `Content-Type` response header when downloading a file needs to *exactly* match what was provided during upload, it does state that it should be the content type of the file, and so homeservers should at least try to get it right.

The original sytest this was taken from, `Can download without a file name locally`, did not check `Content-Header`. I personally think it is valuable to do so, but we may want to make an exception for this modification, as it does seem to be beneficial and not against the spec, however vague it might be.

**Comment by richvdh** [comment]
>  both have a check for the request's Content-Type header value.

which request? The one Complement sends to the server to fetch the media? That seems to make no sense?

**Comment by anoadragon453** [comment]
> > both have a check for the request's Content-Type header value.
> 
> which request? The one Complement sends to the server to fetch the media? That seems to make no sense?

No sorry, the `Content-Type` header of the initial upload media request.

**Comment by Kegsay** [comment]
Maybe just check the mime-type on the Content-Type header and not a literal string match?

**Comment by anoadragon453** [comment]
Right, looks like we can use [`http.DetectContentType`](https://golang.org/pkg/net/http/#DetectContentType) for this.

**Comment by anoadragon453** [comment]
`http.DetectContentType` returns `text/plain; charset=utf-8` lol.

I'll just do a split on the first string before `;`.

**Comment by turt2live** [comment]
fwiw this is a conversation that should happen in the spec at some point - I have fairly strong opinions that the server should not be doing certain things to the header (like interpreting the body to pick a different header) or changing charsets on people, however the spec does indeed do a poor job of explaining what the requirements are. In general, the server is expected to be largely a passthrough for the content-type header, but whether that makes sense or not is a spec concern.

Ideally complement doesn't stray away from the spec like sytest did/does, so it would be good to solve this for everyone and not patch over it.

**Comment by anoadragon453** [comment]
@turt2live Good point. Is there a spec issue for this already?

**Comment by turt2live** [comment]
@anoadragon453 https://github.com/matrix-org/matrix-doc/pull/2701
