### ISSUE TITLE
Add way to enable and disable tests that are using deprecated endpoints 

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/complement#5]

**Comment by Kegsay** [comment]
I was hoping to use `t.Skipf` at the end of the test if a client uses a matched path, but test failures overwrite skipping. Given we need to parse the output though (see #3) we can maybe do a fixed string to mark it as deprecated?

**Comment by Kegsay** [comment]
Usage would be to include a skip path list like:
```
/_matrix/client/v1/events
/_matrix/client/v1/initialSync
```
which then gets matched in the CS API client transport. So technically it doesn't "disable" the test as setup code will run, but it will mark the test in some way.

**Comment by Kegsay** [comment]
I thought about having test metadata but it's a pain to fill out and can get out-of-sync. Better to rely on the actual HTTP requests made.

**Comment by oliverpool** [comment]
What do you think about moving tests of deprecated enpoints to dedicated files with a specific build tags?

One can then run the tests for a given version of the API.

Something like https://stackoverflow.com/a/38439941/3207406

**Comment by Kegsay** [comment]
We already do this for things like benchmarks and (soon) for MSCs, so this is probably the right way to go about it tbh.

**Comment by Kegsay** [comment]
We use build tags for blacklisting stuff now, which is basically the same thing. Closing.
