### ISSUE TITLE
Add Conduit to the recognised Complement homeservers

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/complement#513]
After a short chat with @timokoesters, I think it's time for Complement to start recognising Conduit.

Adding Conduit to `runtime` would enable Timo (and other Conduit maintainers) to add `SkipIf`s to tests at their leasure, and would allow conduit to be ran alongside dendrite and synapse in CI in the future.

**Comment by Orhideous** [comment]
As far as I understand, adding support is just a few lines in [main/runtime/hs.go](https://github.com/matrix-org/complement/tree/main/runtime) + `hs_conduit.go`. Is it so?

**Comment by ShadowJonathan** [comment]
I should mention [this open PR on conduit's side](https://gitlab.com/famedly/conduit/-/merge_requests/404) here, for which I wanted to wait until that was merged before I made a PR here, but over there it hasn't had any movement so far...
