### ISSUE TITLE
Introduce `runtime.ForMatrixVersion`

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/complement#549]
Related to https://github.com/matrix-org/complement/issues/335, and as a related alternative to what I was trying to do in https://github.com/matrix-org/complement/issues/242;

Introduce `runtime.ForMatrixVersion(major, minor uint8)`, which will fetch `/client/versions` and compare if the given version is compatible with any version given.

If not, skip the test.

This'd make it possible for complement to skip whole hosts of tests automatically if the server does not broadcast support for it.

It would also self-document the feature prescribing itself only for/after a certain matrix version, which would help with sorting through them at a later time.

In the future, it could also be possible to do the same for MSCs (via `unstable_features matching, and such)

**Comment by clokep** [comment]
Is the assumption here that `runtime.ForMatrixVersion(1, 4)` would mean that anything >= 1.4 would be OK?

I'm unsure if that's valid.

**Comment by ShadowJonathan** [comment]
`>=1.4,<2.0`, more or less.

Do you think specifying an upper bound (for when a feature is deprecated) is needed?

**Comment by clokep** [comment]
> Do you think specifying an upper bound (for when a feature is deprecated) is needed?

For what we have today, probably not. I guess we could always handle that in the future.

**Comment by kegsay** [comment]
Closing this. We want to move away from Complement dictating what tests are run. Whilst I like the idea of having Complement self-configure itself, it could also be a bit of a nightmare. If `/versions` omits a previously working version, _tests will be skipped and nothing will fail_. This feels like a bad failure mode which can easily be avoided by just stating what versions you support at test execution time.
