### ISSUE TITLE
Event relationship tests seem flakey

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/complement#568]
`TestEventRelationships` and `TestFederatedEventRelationships` seem to turn up repeatedly in CI flakes;
- https://github.com/matrix-org/complement/actions/runs/3496172602/jobs/5853777083
- https://github.com/matrix-org/complement/actions/runs/3497977607/jobs/5857756804

**Comment by richvdh** [comment]
please could you split this up into an issue per test?
