### ISSUE TITLE
Complement `TestDeviceListUpdates/when_joining_a_room_with_a_remote_user` is flakey

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/complement#580]
https://github.com/matrix-org/synapse/actions/runs/3149623842/jobs/5121449618#step:5:8174

Happened in worker mode---would guess there's some race the test isn't expecting?

**Comment by richvdh** [comment]
https://github.com/matrix-org/synapse/actions/runs/3884827892/jobs/6627963686

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/actions/runs/3996958036/jobs/6857752983

**Comment by clokep** [comment]
I had this fail twice yesterday on me:

https://github.com/matrix-org/synapse/actions/runs/4127804842/jobs/7131517396
https://github.com/matrix-org/synapse/actions/runs/4127804842/jobs/7131517530
