### ISSUE TITLE
Allow os.Setenv to pass through to docker containers

### ISSUE THREAD

**Issue by kegsay** [matrix-org/complement#6]
So authors can do stuff like DENDRITE_TRACE_INTERNAL=1

**Comment by reivilibre** [comment]
I'm not sure I understand the title of this issue (`os.Setenv` seems to be a function for setting environment vars?).

However I would also like the ability to pass environment variables through to Synapse's container.
Do we just pass all the variables in, or should we be a bit more cautious (a typical process/shell usually has a lot of ambient environment variables; I don't want to interfere with the reproducibility too much)?
As a first thought: if we care about that, they could be prefixed with a common prefix — not sure what your preference is there?
