### ISSUE TITLE
Add documentation on build tags/homeserver blacklists

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/complement#66]
People may be confused on how exactly to run optional tests, or how they should implement white/blacklists for their homeservers.

I don't think we should document every build tag that's placed in, but just a quick summary of where and why we normally use them would be good.

**Comment by Kegsay** [comment]
https://github.com/matrix-org/complement/commit/5a7037b87853cf9705c81c8c698ff7f270b4cb69
