### ISSUE TITLE
Tail end of server logs appearing above the rest of the logs

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/complement#87]
Logs: [buildkite.log](https://github.com/matrix-org/complement/files/6117596/buildkite.log)

At line 1974 in the log file you can see that I seem to be experiencing logs being cut off when I have quite a lot of them.

Interestingly it actually looks like a chunk of logs are being spurted out, before Complement actually prints them on line 2518.

And if you look at the end of the actual logs... that lines up with the beginning of the spurted out logs.

So somehow the tail end of the server logs are being printed out above the rest of them...

I initially wondered if this was a bug with piping the logs to `less` and viewing them there. But the same happens even without `less` involved.

**Comment by Kegsay** [comment]
Do you experience this when running complement locally?

**Comment by anoadragon453** [comment]
Sorry, some useful information may be that this was buildkite running locally on my laptop.

But indeed, I do not seem to experience the issue when running the same commands (and **without** `CI=true`) on the same machine.

**Comment by kegsay** [comment]
Closing this on the basis that no one else seems to have noticed this, and you don't experience this when running locally. This could have been a buildkite thing.
